# Generated by Django 3.2.3 on 2023-05-23 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=30)),
                ('port', models.CharField(max_length=10)),
                ('protocol_type', models.CharField(choices=[('one', 'two'), ('three', 'four')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.CharField(max_length=30)),
                ('y', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('nominal_capacity', models.DecimalField(decimal_places=3, max_digits=7)),
                ('operational_capacity', models.DecimalField(decimal_places=3, max_digits=7)),
                ('modules', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='station.module')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('one', 'two'), ('three', 'four')], max_length=10)),
                ('model', models.CharField(max_length=30)),
                ('sampling_rate', models.CharField(max_length=30)),
                ('operational_capacity', models.DecimalField(decimal_places=3, max_digits=7)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='station.module')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='sensors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='station.sensor'),
        ),
        migrations.AddField(
            model_name='module',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station.station'),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=7)),
                ('unit', models.CharField(choices=[('this', 'that'), ('that', 'that')], max_length=10)),
                ('type', models.CharField(choices=[('this', 'that'), ('that', 'that')], max_length=10)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('modules', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station.module')),
            ],
        ),
    ]
