# Generated by Django 3.2.3 on 2023-05-23 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='type',
            field=models.CharField(choices=[('one', 'two'), ('three', 'four')], max_length=10),
        ),
        migrations.AlterField(
            model_name='log',
            name='unit',
            field=models.CharField(choices=[('one', 'two'), ('three', 'four')], max_length=10),
        ),
        migrations.AlterField(
            model_name='module',
            name='sensors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='station.sensor'),
        ),
    ]
